[phases.setup]
nixPkgs = ["python39", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p data/embeddings data/processed_docs data/cache logs"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
